version: '3.8'

services:
  app:
    container_name: react-frontend-app-dev
    image: react-frontend-app-dev
    # env_file:
    #   - .env.development
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
