export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR';

export const GET_POSTS_BY_ID_REQUEST = 'GET_POSTS_BY_ID_REQUEST';
export const GET_POSTS_BY_ID_SUCCESS = 'GET_POSTS_BY_ID_SUCCESS';
export const GET_POSTS_BY_ID_ERROR = 'GET_POSTS_BY_ID_ERROR';

export const CREATE_POSTS_REQUEST = 'CREATE_POSTS_REQUEST';
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS';
export const CREATE_POSTS_ERROR = 'CREATE_POSTS_ERROR';

export const UPDATE_POSTS_REQUEST = 'UPDATE_POSTS_REQUEST';
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS';
export const UPDATE_POSTS_ERROR = 'UPDATE_POSTS_ERROR';

export const DELETE_POSTS_REQUEST = 'DELETE_POSTS_REQUEST';
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS';
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR';
